version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: ./dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 8888:8000
    env_file:
      - .env
    networks:
      - web
    depends_on:
      - db

  db:
    image: postgres:15.6
    volumes:
      - db_store:/var/lib/postgresql/data/
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - web
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "${POSTGRES_USER}", "-d", "harmonycal"]
      interval: 5s
      timeout: 20s
      retries: 10

      
networks:
  web:

volumes:
  db_store:
