version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: ./backend/dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - 8888:8888
    env_file:
      - .env
    networks:
      - web
    depends_on:
      - db

  db:
    image: postgres:15.6
    volumes:
      - db_store:/var/lib/postgresql/data/
      - ./backend/db/init:/docker-entrypoint-initdb.d 
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - web
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "harmonycal"]
      interval: 5s
      timeout: 20s
      retries: 10
      
networks:
  web:

volumes:
  db_store:
