FROM python:3.11.2-buster

WORKDIR /backend

COPY ./backend .

RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

CMD [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8888" ]

